#!/bin/bash

# if brew is not installed, install it
if ! command -v brew &> /dev/null
then
		echo "brew could not be found, installing..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [[ "$OS" == 'Darwin' ]]; then
  export BREW_HOME=/opt/homebrew/bin
else
  export BREW_HOME=/home/linuxbrew/.linuxbrew/bin
fi

# install all the packages
$BREW_HOME/brew install -q \
	aws-vault \
	awscli \
	k9s \
	krew \
	kubectl
